# Generated by Django 4.2.3 on 2023-08-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('msg', models.CharField(max_length=50)),
            ],
        ),
    ]
